Repository OpenZeppelin/openzeppelin-sdk, pull requests merged in 2018-11, with the labels that each got.

#415 Do not delete deployment info from other networks in truffle artifacts
  packages/cli/src/models/network/NetworkAppController.js
Labels: kind:bug

#299 Estimate gas price
  packages/lib/package-lock.json
  packages/lib/package.json
  packages/lib/src/utils/Transactions.js
  packages/lib/test/src/utils/Transactions.test.js
Labels: status:in-progress

#310 Use contract method `estimateGas` function instead of `web3.eth.estimateGas` for contract method calls
  packages/lib/src/utils/Transactions.js
  packages/lib/test/src/utils/Transactions.test.js
Labels: status:on-hold
