Repository OpenZeppelin/openzeppelin-sdk, pull requests merged in 2018-10, with the labels that each got.

#169 Re-throw App or Lib deployment errors
  packages/cli/src/models/network/NetworkAppController.js
  packages/cli/src/models/network/NetworkBaseController.js
  packages/cli/src/models/network/NetworkLibController.js
  packages/cli/src/models/network/ProjectDeployer.js
  packages/cli/src/scripts/status.js
Labels: status:ready-to-merge

#167 Check isConstructor for running initializable
  packages/lib/contracts/Initializable.sol
Labels: status:ready-to-merge

#184 Fix integration tests using v2.0.0-alpha.2
  packages/cli/package-lock.json
  packages/docs/docs/docs/api_application_Package.md
  packages/lib/package-lock.json
  packages/vouching/package-lock.json
  tests/cli-app/files/package.json.v1
  tests/cli-app/files/package.json.v2
Labels: status:ready-to-merge

#197 Improve ABI parsing for initialization
  packages/cli/src/models/local/LocalBaseController.js
  packages/lib/contracts/mocks/GetFunctionMocks.sol
  packages/lib/src/index.js
  packages/lib/src/utils/ABIs.js
  packages/lib/src/utils/ContractAST.js
  packages/lib/test/src/utils/ABIs.test.js
  tests/cli-app/dependencies/mock-stdlib-1.1.0/build/contracts/Greeter.json
  tests/cli-app/dependencies/mock-stdlib-1.1.0/build/contracts/Parent.json
  tests/cli-app/dependencies/mock-stdlib-1.1.0/contracts/Parent.sol
  tests/cli-app/dependencies/mock-stdlib-1.2.0/build/contracts/Greeter.json
  tests/cli-app/dependencies/mock-stdlib-1.2.0/build/contracts/Parent.json
  tests/cli-app/dependencies/mock-stdlib-1.2.0/contracts/Parent.sol
  tests/cli-app/files/Samples.sol
  tests/cli-app/files/SamplesV2.sol
Labels: status:ready-to-merge

#200 Refuse to run transactions with truffle default gas price
  packages/lib/src/utils/Contracts.js
  packages/lib/src/utils/Transactions.js
  packages/lib/test/src/utils/Transactions.test.js
  tests/cli-app/workdir/truffle.js
Labels: status:ready-to-merge

#209 Throw error if provided network is not defined
  packages/cli/src/utils/runWithTruffle.js
Labels: status:ready-to-merge

#215 Added a storage gap at the end of Initializable's storage layout.
  packages/lib/contracts/Initializable.sol
  packages/lib/test/contracts/upgradeability/AdminUpgradeabilityProxy.test.js
Labels: status:ready-to-merge

#217 Removed dependency names can no longer be reused.
  packages/vouching/contracts/Vouching.sol
  packages/vouching/test/contracts/Vouching.test.js
Labels: status:ready-to-merge

#218 Pinned the Solidity doc links to v0.4.24
  packages/lib/contracts/application/App.sol
  packages/lib/contracts/upgradeability/AdminUpgradeabilityProxy.sol
  packages/lib/contracts/upgradeability/UpgradeabilityProxy.sol
Labels: status:ready-to-merge

#227 Fixed wrong unvouching test.
  packages/vouching/test/contracts/Vouching.test.js
Labels: status:ready-to-merge

#225 Vouching.create now requires the dependency address to be a contract.
  packages/vouching/contracts/Vouching.sol
  packages/vouching/contracts/mocks/DependencyMock.sol
  packages/vouching/test/contracts/Vouching.test.js
Labels: status:ready-to-merge

#231 Apps are lightweight by default
  packages/cli/src/commands/init.js
  packages/cli/src/commands/push.js
  packages/cli/src/models/files/ZosPackageFile.js
  packages/cli/src/models/local/LocalAppController.js
  packages/cli/src/models/network/NetworkAppController.js
  packages/cli/src/models/network/NetworkBaseController.js
  packages/cli/src/models/network/ProjectDeployer.js
  packages/cli/src/scripts/init.js
  packages/cli/src/scripts/push.js
  packages/cli/test/commands/add.test.js
  packages/cli/test/commands/bump.test.js
  packages/cli/test/commands/init.test.js
  packages/cli/test/commands/link.test.js
  packages/cli/test/commands/push.test.js
  packages/cli/test/commands/remove.test.js
  packages/cli/test/commands/unlink.test.js
  packages/cli/test/mocks/packages/package-empty-lite.zos.json
  packages/cli/test/mocks/packages/package-empty.zos.json
  packages/cli/test/mocks/packages/package-unsupported-zosversion.zos.json
  packages/cli/test/mocks/packages/package-with-contracts-and-multiple-stdlibs.zos.json
  packages/cli/test/mocks/packages/package-with-contracts-and-stdlib-v2.zos.json
  packages/cli/test/mocks/packages/package-with-contracts-and-stdlib.zos.json
  packages/cli/test/mocks/packages/package-with-contracts-v2.zos.json
  packages/cli/test/mocks/packages/package-with-contracts.zos.json
  packages/cli/test/mocks/packages/package-with-invalid-contracts.zos.json
  packages/cli/test/mocks/packages/package-with-invalid-stdlib.zos.json
  packages/cli/test/mocks/packages/package-with-multiple-stdlibs.zos.json
  packages/cli/test/mocks/packages/package-with-stdlib-range.zos.json
  packages/cli/test/mocks/packages/package-with-stdlib.zos.json
  packages/cli/test/mocks/packages/package-with-undeployed-stdlib.zos.json
  packages/cli/test/models/TestHelper.test.js
  packages/cli/test/scripts/create.test.js
  packages/cli/test/scripts/init.test.js
  packages/cli/test/scripts/push.test.js
  packages/cli/test/scripts/status.test.js
  packages/cli/test/scripts/update.test.js
  packages/lib/src/project/AppProject.js
  packages/lib/src/project/BasePackageProject.js
  packages/lib/src/project/SimpleProject.js
  packages/lib/test/src/project/AppProject.test.js
  packages/vouching/zos.json
  tests/cli-app/test/integration.test.js
Labels: status:ready-to-merge

#214 Add skip-compile option to push options
  packages/cli/src/bin/options.js
  packages/cli/src/commands/add.js
Labels: status:ready-to-merge

#224 Validate contracts on push instead of add
  packages/cli/contracts/mocks/Imports.sol
  packages/cli/src/interface/ValidationLogger.js
  packages/cli/src/interface/Validations.js
  packages/cli/src/models/files/ZosNetworkFile.js
  packages/cli/src/models/local/LocalBaseController.js
  packages/cli/src/models/network/NetworkBaseController.js
  packages/cli/src/scripts/add.js
  packages/cli/test/interface/ValidationLogger.test.js
  packages/cli/test/scripts/add.test.js
  packages/cli/test/scripts/push.test.js
  packages/lib/contracts/mocks/Invalid.sol
  packages/lib/contracts/mocks/StorageMocks3.sol
  packages/lib/contracts/mocks/StorageMocksForComparison.sol
  packages/lib/contracts/mocks/WithInitialize.sol
  packages/lib/src/index.js
  packages/lib/src/validations/Constructors.js
  packages/lib/src/validations/Initializers.js
  packages/lib/src/validations/Instructions.js
  packages/lib/src/validations/index.js
  packages/lib/test/src/validations/Layout.test.js
  packages/lib/test/src/validations/Validations.test.js
Labels: status:ready-to-merge

#236 Improved ZEP-TPL interaction documentation and tests
  packages/vouching/contracts/ZEPToken.sol
  packages/vouching/test/contracts/ZEPToken.test.js
Labels: status:ready-to-merge

#230 Add new check command
  packages/cli/src/commands/check.js
  packages/cli/src/commands/index.js
  packages/cli/src/models/files/ZosPackageFile.js
  packages/cli/src/models/local/LocalBaseController.js
  packages/cli/src/scripts/add.js
  packages/cli/src/scripts/check.js
  packages/cli/test/commands/check.test.js
  packages/cli/test/commands/share.js
  packages/cli/test/scripts/check.test.js
  packages/lib/src/utils/Contracts.js
Labels: status:ready-to-merge

#241 Detect initial values in fields declarations
  packages/cli/src/interface/ValidationLogger.js
  packages/cli/test/interface/ValidationLogger.test.js
  packages/lib/contracts/mocks/WithInitialValues.sol
  packages/lib/src/validations/InitialValues.js
  packages/lib/src/validations/index.js
  packages/lib/test/src/validations/Validations.test.js
Labels: status:ready-to-merge

#213 Use canonical network names for zos network files
  packages/cli/src/models/truffle/Truffle.js
  packages/cli/src/utils/runWithTruffle.js
  tests/cli-app/test/share.js
  tests/cli-app/workdir/scripts/run.js
  tests/cli-app/workdir/scripts/shared.js
Labels: status:ready-to-merge

#208 Link solidity libraries
  packages/cli/contracts/mocks/ImplV1.sol
  packages/cli/contracts/mocks/ImplV2.sol
  packages/cli/contracts/mocks/Imports.sol
  packages/cli/contracts/mocks/Libraries.sol
  packages/cli/src/models/dependency/Dependency.js
  packages/cli/src/models/files/ZosNetworkFile.js
  packages/cli/src/models/files/ZosPackageFile.js
  packages/cli/src/models/network/NetworkBaseController.js
  packages/cli/src/models/network/NetworkLibController.js
  packages/cli/src/models/status/StatusChecker.js
  packages/cli/src/models/status/StatusComparator.js
  packages/cli/src/models/status/StatusFetcher.js
  packages/cli/src/utils/runWithTruffle.js
  packages/cli/test/mocks/mock-stdlib/build/contracts/GreeterImpl.json
  packages/cli/test/mocks/mock-stdlib/build/contracts/GreeterLib.json
  packages/cli/test/mocks/mock-stdlib/contracts/GreeterImpl.sol
  packages/cli/test/mocks/mock-stdlib/contracts/GreeterLib.sol
  packages/cli/test/mocks/packages/package-lib-with-contracts-v2.zos.json
  packages/cli/test/mocks/packages/package-lib-with-contracts.zos.json
  packages/cli/test/mocks/packages/package-with-contracts-v2.zos.json
  packages/cli/test/mocks/packages/package-with-contracts.zos.json
  packages/cli/test/models/Dependency.test.js
  packages/cli/test/models/StatusComparator.test.js
  packages/cli/test/models/StatusFetcher.test.js
  packages/cli/test/models/TestHelper.test.js
  packages/cli/test/scripts/add.test.js
  packages/cli/test/scripts/create.test.js
  packages/cli/test/scripts/push.test.js
  packages/cli/test/scripts/remove.test.js
  packages/cli/test/scripts/set-admin.test.js
  packages/cli/test/scripts/status.test.js
  packages/cli/test/scripts/update.test.js
  packages/cli/test/scripts/verify.test.js
  packages/lib/src/index.js
  packages/lib/src/project/BasePackageProject.js
  packages/lib/src/utils/Bytecode.js
  packages/lib/src/utils/Contracts.js
  tests/cli-app/dependencies/mock-stdlib-1.1.0/build/contracts/Greeter.json
  tests/cli-app/dependencies/mock-stdlib-1.1.0/build/contracts/Numbers.json
  tests/cli-app/dependencies/mock-stdlib-1.1.0/build/contracts/Parent.json
  tests/cli-app/dependencies/mock-stdlib-1.1.0/build/contracts/SharedNumbers.json
  tests/cli-app/dependencies/mock-stdlib-1.1.0/contracts/Greeter.sol
  tests/cli-app/dependencies/mock-stdlib-1.1.0/contracts/InternalLibrary.sol
  tests/cli-app/dependencies/mock-stdlib-1.1.0/contracts/SharedLibrary.sol
  tests/cli-app/dependencies/mock-stdlib-1.2.0/build/contracts/Greeter.json
  tests/cli-app/dependencies/mock-stdlib-1.2.0/build/contracts/Numbers.json
  tests/cli-app/dependencies/mock-stdlib-1.2.0/build/contracts/Parent.json
  tests/cli-app/dependencies/mock-stdlib-1.2.0/build/contracts/SharedNumbers.json
  tests/cli-app/dependencies/mock-stdlib-1.2.0/contracts/Greeter.sol
  tests/cli-app/dependencies/mock-stdlib-1.2.0/contracts/InternalLibrary.sol
  tests/cli-app/dependencies/mock-stdlib-1.2.0/contracts/SharedLibrary.sol
  tests/cli-app/files/GreeterWrapperV2.sol
  tests/cli-app/test/integration.test.js
  tests/cli-app/test/project.js
Labels: status:review

#229 Enhance cli outputs on error
  packages/cli/src/bin/errors.js
  packages/cli/src/models/errors/ErrorHandler.js
  packages/cli/src/models/errors/ScriptError.js
  packages/cli/src/models/files/ZosNetworkFile.js
  packages/cli/src/models/network/NetworkBaseController.js
  packages/cli/src/scripts/create.js
  packages/cli/src/scripts/freeze.js
  packages/cli/src/scripts/pull.js
  packages/cli/src/scripts/push.js
  packages/cli/src/scripts/set-admin.js
  packages/cli/src/scripts/update.js
  packages/cli/test/commands/share.js
Labels: status:review

#228 Added 'Safety checks' section to docs and linked to it from add command.
  packages/cli/src/interface/ValidationLogger.js
  packages/docs/docs/docs/advanced.md
Labels: kind:documentation

#226 Renamed "standard libraries" to "EVM packages"
  README.md
  examples/lib-complex/index.js
  packages/README.md
  packages/docs/docs/docs/advanced.md
  packages/docs/docs/docs/basil.md
  packages/docs/docs/docs/building.md
  packages/docs/docs/docs/crafty.md
  packages/docs/docs/docs/developing.md
  packages/docs/docs/docs/erc20_onboarding.md
  packages/docs/docs/docs/low_level_app.md
  packages/docs/docs/docs/start.md
  packages/docs/docs/docs/stdlib.md
  packages/docs/docs/docs/testing.md
  packages/docs/docs/docs/using.md
  packages/docs/docs/website/i18n/en.json
Labels: kind:documentation

#262 docs: add algolia search
  packages/docs/docs/website/siteConfig.js
Labels: kind:documentation

#260 docs: remove and extra } and fixed spacing on css
  packages/docs/docs/website/static/css/custom.css
Labels: kind:documentation

#279 Update dependencies version on push
  packages/cli/src/models/network/NetworkAppController.js
  packages/cli/test/scripts/push.test.js
Labels: status:ready-to-merge

#280 Reupload contract if related lib has changed
  packages/cli/src/models/files/ZosNetworkFile.js
  packages/cli/src/models/network/NetworkBaseController.js
  packages/cli/test/scripts/push.test.js
Labels: status:ready-to-merge

#281 Use version of dependency for identifying proxies in network json file
  packages/cli/src/models/network/NetworkAppController.js
  packages/cli/test/scripts/create.test.js
  packages/cli/test/scripts/update.test.js
Labels: status:ready-to-merge

#285 Check if project is published before freeze
  packages/cli/src/models/network/NetworkBaseController.js
  packages/cli/test/scripts/freeze.test.js
Labels: status:ready-to-merge

#286 Fix storage layout parsing when there are complex types
  packages/lib/contracts/mocks/StorageMocksForComparison.sol
  packages/lib/src/validations/Storage.js
  packages/lib/test/src/validations/Layout.test.js
  packages/lib/test/src/validations/Storage.test.js
Labels: status:ready-to-merge

#289 Change status fix/fetch error message
  packages/cli/src/models/network/NetworkBaseController.js
Labels: status:review

#301 Preserve stack trace when using DeployError
  packages/lib/src/project/AppProject.js
  packages/lib/src/project/LibProject.js
  packages/lib/src/utils/errors/DeployError.js
Labels: status:ready-to-merge

#222 Updates documentation about json files regarding lightmode.
  packages/docs/docs/docs/advanced.md
Labels: kind:documentation

#273 Adds a new "migrating from 1.x to 2.x" section to the documentation
  packages/docs/docs/docs/new_2.x
  packages/docs/docs/website/sidebars.json
Labels: kind:documentation

#288 Adds a new section to the documentation on "proxy patterns"
  packages/docs/docs/docs/advanced.md
  packages/docs/docs/docs/proxies.md
Labels: kind:documentation

#239 Added first draft of a new 'architecture' section.
  packages/docs/docs/docs/architecture.md
  packages/docs/docs/website/i18n/en.json
  packages/docs/docs/website/sidebars.json
  packages/docs/docs/website/static/img/zos2.png
Labels: kind:documentation

#325 docs: fix typo
  packages/docs/docs/docs/writing_contracts.md
Labels: kind:documentation

#324 docs: update writing contracts to openzeppelin-eth
  packages/docs/docs/docs/writing_contracts.md
Labels: kind:documentation

#323 docs: update references to openzeppelin-eth in architecture
  packages/docs/docs/docs/architecture.md
Labels: kind:documentation

#322 docs: remove confusing note about contructors
  packages/docs/docs/docs/writing_contracts.md
Labels: kind:documentation

#319 docs: fix formatting of the proxy pattern diagram
  packages/docs/docs/docs/proxies.md
Labels: kind:documentation

#318 docs: fix titles on what's new on 2.x
  packages/docs/docs/docs/new_2.x
Labels: kind:documentation

#317 docs: the description of the new 2.x commands is no longer on the page
  packages/docs/docs/docs/new_2.x
Labels: kind:discussion

#316 docs: add a link to report bugs in the footer
  packages/docs/docs/website/core/Footer.js
  packages/docs/docs/website/static/css/custom.css
Labels: kind:documentation

#315 Replace all the usages of zOS with ZeppelinOS
  LICENSE
  packages/cli/LICENSE
  packages/cli/src/models/Verifier.js
  packages/cli/src/models/local/ControllerFor.js
  packages/docs/LICENSE
  packages/docs/docs/docs/architecture.md
  packages/docs/docs/docs/new_2.x
  packages/docs/docs/docs/proxies.md
  packages/docs/docs/website/core/Footer.js
  packages/docs/docs/website/siteConfig.js
  packages/lib/LICENSE
Labels: kind:documentation

#313 Update the favicon with the new ZeppelinOS logo
  packages/docs/docs/website/static/img/favicon.png
Labels: kind:documentation

#336 docs: fix the code blocks
  packages/docs/docs/docs/architecture.md
  packages/docs/docs/docs/deploying.md
  packages/docs/docs/docs/erc20_onboarding.md
  packages/docs/docs/docs/linking.md
  packages/docs/docs/docs/mainnet.md
  packages/docs/docs/docs/pattern.md
  packages/docs/docs/docs/publish.md
  packages/docs/docs/docs/testing.md
  packages/docs/docs/docs/upgradeability_governance.md
  packages/docs/docs/docs/upgrading.md
  packages/docs/docs/docs/writing_contracts.md
  packages/docs/docs/docs/zos_lib.md
Labels: kind:documentation

#335 docs: remove the NODE_ENV workaround
  packages/docs/docs/docs/deploying.md
  packages/docs/docs/docs/linking.md
  packages/docs/docs/docs/upgrading.md
Labels: kind:documentation

#330 Corrected links to sub-sections of advanced.md that were removed.
  packages/docs/docs/docs/erc20_onboarding.md
  packages/docs/docs/docs/new_2.md
  packages/docs/docs/docs/writing_contracts.md
  packages/docs/docs/website/versioned_docs/version-1.0.0/building.md
  packages/docs/docs/website/versioned_docs/version-1.0.0/low_level_contract.md
Labels: kind:documentation

#347 Adds natspec documentation to the vouching package (CLEANER VERSION)
  packages/docs/scripts/bump-docs.js
  packages/docs/scripts/generators.js
  packages/vouching/contracts/Vouching.sol
  packages/vouching/contracts/ZEPToken.sol
  packages/vouching/package.json
Labels: kind:documentation

#348 Replaces usages of zos.local.json with zos.dev-<...>.json
  packages/docs/docs/docs/configuration.md
  packages/docs/docs/docs/deploying.md
  packages/docs/docs/docs/erc20_onboarding.md
  packages/docs/docs/docs/linking.md
  packages/docs/docs/docs/publish.md
  packages/docs/docs/docs/upgrading.md
Labels: kind:documentation

#361 Added comments about zos json files in vcs.
  packages/docs/docs/docs/configuration.md
Labels: kind:documentation

#365 Fix in docs styles
  packages/docs/docs/website/siteConfig.js
  packages/docs/docs/website/static/css/custom.css
Labels: kind:documentation, status:review

#360 Update ERC20 onboarding guide
  packages/docs/docs/docs/configuration.md
  packages/docs/docs/docs/erc20_onboarding.md
Labels: kind:documentation

#331 Add a new 'ZEPToken' section to the documentation
  packages/docs/docs/docs/zeptoken.md
  packages/docs/docs/website/sidebars.json
Labels: kind:documentation

#346 Minor fixes to doc files
  packages/docs/docs/docs/configuration.md
  packages/docs/docs/docs/deploying.md
  packages/docs/docs/docs/linking.md
  packages/docs/docs/docs/new_2.md
  packages/docs/docs/docs/pattern.md
  packages/docs/docs/docs/publish.md
  packages/docs/docs/docs/upgrading.md
  packages/docs/docs/docs/writing_contracts.md
Labels: kind:documentation

#334 docs: avoid the use of upgradeability
  packages/docs/docs/docs/erc20_onboarding.md
  packages/docs/docs/docs/new_2.md
  packages/docs/docs/docs/pattern.md
  packages/docs/docs/docs/upgrades_governance.md
  packages/docs/docs/website/sidebars.json
Labels: kind:documentation

#333 docs: update the testing guide
  packages/docs/docs/docs/testing.md
Labels: kind:documentation

#359 Do not check gas price if working on ganache
  packages/lib/src/utils/Transactions.js
  packages/lib/test/src/utils/Transactions.test.js
Labels: status:ready-to-merge

#378 docs: add a link to the difference between openzeppelin-solidity and openzeppelin-eth
  packages/docs/docs/docs/linking.md
Labels: kind:documentation

#377 docs: remove spurious character
  packages/docs/docs/docs/erc20_onboarding.md
Labels: kind:documentation

#376 docs: fix link to constructor caveat
  packages/docs/docs/docs/new_2.md
  packages/docs/docs/docs/writing_contracts.md
Labels: kind:documentation

#379 docs: fix link to diagram
  packages/docs/docs/docs/architecture.md
Labels: kind:documentation

#368 Fix docs links to GH to use tagged version
  packages/docs/docs/docs/architecture.md
  packages/docs/docs/docs/testing.md
  packages/docs/docs/docs/zeptoken.md
Labels: kind:documentation

#375 docs: fix titles in the pattern page
  packages/docs/docs/docs/pattern.md
Labels: kind:documentation

#374 docs: fix the possesive form of ZeppelinOS
  packages/docs/docs/docs/new_2.md
  packages/docs/docs/docs/zeptoken.md
Labels: kind:documentation

#362 Review security warnings messages and capture them in docs
  packages/cli/src/interface/ValidationLogger.js
  packages/cli/test/interface/ValidationLogger.test.js
  packages/docs/docs/docs/writing_contracts.md
Labels: kind:documentation

#373 docs: update ZEPToken to Vouching
  packages/docs/docs/docs/vouching.md
  packages/docs/docs/website/sidebars.json
Labels: kind:documentation

#371 Add create proxy example with multiple args
  packages/docs/docs/docs/deploying.md
  packages/docs/docs/docs/upgrading.md
Labels: kind:documentation, status:on-hold

#383 docs: polish the deploying guide
  packages/docs/docs/docs/deploying.md
Labels: kind:documentation

#370 Replace `truffle develop` with `truffle console` + ganache
  packages/docs/docs/docs/deploying.md
  packages/docs/docs/docs/erc20_onboarding.md
  packages/docs/docs/docs/upgrading.md
  packages/docs/docs/docs/zos_lib.md
Labels: kind:documentation

#384 docs: explain why the config files must be published
  packages/docs/docs/docs/publish.md
Labels: kind:documentation

#398 Update zos json file formats to v2
  packages/docs/docs/docs/configuration.md
Labels: kind:documentation

#400 Remove whitespace from beginning of testing .md
  packages/docs/docs/docs/testing.md
Labels: kind:documentation

#399 Explanation on transparent proxies
  packages/docs/docs/docs/pattern.md
Labels: kind:documentation

#393 Improve whats new in v2 commands section
  packages/docs/docs/docs/new_2.md
Labels: kind:documentation

#397 Improve quickstart guide to work with session
  packages/docs/docs/docs/deploying.md
  packages/docs/docs/docs/linking.md
  packages/docs/docs/docs/upgrading.md
Labels: kind:documentation

#408 Add token mechanics section to the docs
  packages/docs/docs/docs/token_mechanics.md
  packages/docs/docs/website/sidebars.json
Labels: kind:documentation
