Repository OpenZeppelin/openzeppelin-sdk, pull requests merged in 2019-10, with the labels that each got.

#1194 Usage with truffle
  packages/docs/modules/ROOT/nav.adoc
  packages/docs/modules/ROOT/pages/truffle.adoc
Labels: kind:documentation

#1226 Implement telemetry in cli
  examples/lib-complex/package-lock.json
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/commands/accounts.ts
  packages/cli/src/commands/add.ts
  packages/cli/src/commands/balance.ts
  packages/cli/src/commands/bump.ts
  packages/cli/src/commands/call.ts
  packages/cli/src/commands/check.ts
  packages/cli/src/commands/compile.ts
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/create2.ts
  packages/cli/src/commands/freeze.ts
  packages/cli/src/commands/init.ts
  packages/cli/src/commands/link.ts
  packages/cli/src/commands/publish.ts
  packages/cli/src/commands/push.ts
  packages/cli/src/commands/remove.ts
  packages/cli/src/commands/send-tx.ts
  packages/cli/src/commands/session.ts
  packages/cli/src/commands/set-admin.ts
  packages/cli/src/commands/transfer.ts
  packages/cli/src/commands/unlink.ts
  packages/cli/src/commands/unpack.ts
  packages/cli/src/commands/update.ts
  packages/cli/src/commands/verify.ts
  packages/cli/src/models/config/ConfigManager.ts
  packages/cli/src/models/config/NetworkConfig.ts
  packages/cli/src/models/config/TruffleConfig.ts
  packages/cli/src/models/files/ProjectFile.ts
  packages/cli/src/scripts/interfaces.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/src/telemetry/send-to-firebase.ts
  packages/cli/test/commands/share.js
  packages/cli/test/prompts/prompt.test.js
  packages/cli/test/telemetry.test.js
  packages/docs/modules/ROOT/pages/faq.adoc
  packages/lib/package-lock.json
  tests/cli/workdir/package-lock.json
Labels: status:ready-to-merge

#1241 Fix Lerna issues? Migrate to Yarn workspaces
  .circleci/config.yml
  HACKING.md
  examples/cli-create2/package-lock.json
  examples/creating-instances-from-solidity/package-lock.json
  examples/creating-instances-from-solidity/package.json
  examples/first-project/.openzeppelin/project.json
  examples/first-project/package-lock.json
  examples/first-project/package.json
  examples/first-project/scripts/test-ci.sh
  examples/lib-complex/package-lock.json
  examples/lib-complex/package.json
  examples/lib-complex/test/behaviors/Donations.behavior.js
  examples/lib-complex/test/behaviors/DonationsWithTokens.behavior.js
  examples/lib-complex/test/helpers/getBalance.js
  examples/lib-complex/truffle.js
  examples/lib-simple/package-lock.json
  examples/linking-contracts/package-lock.json
  examples/truffle-migrate/package-lock.json
  lerna.json
  package-lock.json
  package.json
  packages/cli/package-lock.json
  packages/cli/src/scripts/interfaces.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/test/models/Dependency.test.js
  packages/docs/package-lock.json
  packages/docs/yarn.lock
  packages/lib/package-lock.json
  tests/cli/dependencies/mock-stdlib-1.2.0/package.json
  tests/cli/test/package-lock.json
  tests/cli/test/src/project.js
  tests/cli/workdir/.gitignore
  tests/cli/workdir/package-lock.json
  tests/kits/test/package-lock.json
  tests/kits/test/src/integration.test.js
  tests/util/share.js
  yarn.lock
Labels: status:review

#1266 Add week number to telemetry report
  packages/cli/src/telemetry/send-to-firebase.ts
Labels: status:ready-to-merge
