Repository OpenZeppelin/openzeppelin-sdk, pull requests merged in 2019-04, with the labels that each got.

#789 Fix in upgrading guide
  packages/docs/docs/website/versioned_docs/version-2.1.0/upgrading.md
  packages/docs/docs/website/versioned_docs/version-2.2.0/upgrading.md
Labels: status:review

#788 feature/check address prior running create2 #774
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/test/scripts/create.test.js
Labels: status:ready-to-merge

#775 Add test to truffle-migrate example #767
  examples/truffle-migrate/index.js
Labels: status:ready-to-merge

#786 Fix in ZWeb3 initializer
  packages/cli/src/models/TestHelper.ts
  packages/lib/src/artifacts/ZWeb3.ts
  packages/lib/test/src/artifacts/ZWeb3.test.js
Labels: status:ready-to-merge

#807 Fix CI if only is present on tests
  packages/cli/truffle.js
  packages/lib/truffle-config.js
Labels: status:ready-to-merge

#804 Adds ability to change owner of a proxy admin to set-admin command
  packages/cli/src/commands/set-admin.ts
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/src/scripts/set-admin.ts
  packages/cli/test/commands/setAdmin.test.js
  packages/cli/test/scripts/set-admin.test.js
  packages/lib/src/project/AppProject.ts
  packages/lib/src/project/ProxyAdminProject.ts
  packages/lib/src/proxy/ProxyAdmin.ts
  packages/lib/test/src/ProxyAdmin.test.js
  packages/lib/test/src/project/AdminProxy.behaviour.js
  packages/lib/test/src/project/AppProject.test.js
  packages/lib/test/src/project/ProxyAdminProject.test.js
  packages/lib/test/src/project/ProxyProject.behaviour.js
Labels: status:in-progress

#810 Fix Contract#at to create a clone of the current instance
  examples/creating-instances-from-solidity/index.js
  packages/cli/test/models/TestHelper.test.js
  packages/lib/src/artifacts/Contract.ts
  packages/lib/test/src/artifacts/Contract.test.js
Labels: status:ready-to-merge

#811 Add test to check for unlinked libraries on deploy
  packages/lib/contracts/mocks/WithLibrary.sol
  packages/lib/test/src/utils/Transactions.test.js
Labels: status:ready-to-merge

#815 Eliminates ProxyAdmin code duplication in ProxyAdminProject and AppProject using TypeScript Mixins
  packages/lib/src/project/AppProject.ts
  packages/lib/src/project/ProxyAdminProject.ts
  packages/lib/src/project/mixin/ProxyAdminProjectMixin.ts
  packages/lib/src/utils/Mixin.ts
Labels: kind:refactor, kind:research

#792 Remaining interactive commands
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/commands/add.ts
  packages/cli/src/commands/bump.ts
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/create2.ts
  packages/cli/src/commands/init.ts
  packages/cli/src/commands/link.ts
  packages/cli/src/commands/publish.ts
  packages/cli/src/commands/push.ts
  packages/cli/src/commands/remove.ts
  packages/cli/src/commands/session.ts
  packages/cli/src/commands/set-admin.ts
  packages/cli/src/commands/unlink.ts
  packages/cli/src/commands/update.ts
  packages/cli/src/commands/verify.ts
  packages/cli/src/models/compiler/Compiler.ts
  packages/cli/src/models/files/ZosNetworkFile.ts
  packages/cli/src/models/initializer/ConfigVariablesInitializer.ts
  packages/cli/src/models/initializer/truffle/Truffle.ts
  packages/cli/src/models/local/LocalController.ts
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/src/models/network/Session.ts
  packages/cli/src/prompts/init-params.ts
  packages/cli/src/prompts/migrations.ts
  packages/cli/src/prompts/prompt.ts
  packages/cli/src/utils/input.ts
  packages/cli/src/utils/prompt.ts
  packages/cli/test/commands/create.test.js
  packages/cli/test/commands/session.test.js
  packages/cli/test/commands/share.js
  packages/cli/test/commands/update.test.js
  packages/cli/test/initializer/truffle/Truffle.test.js
  packages/cli/test/models/ZosPackageFile.test.js
  packages/cli/test/prompts/prompt.test.js
  packages/cli/test/scripts/update.test.js
  packages/cli/test/setup.js
  packages/cli/test/utils/input.test.js
  packages/cli/test/utils/prompt.test.js
  packages/lib/contracts/mocks/InitializableMock.sol
  packages/lib/package-lock.json
  packages/lib/src/application/App.ts
  packages/lib/src/artifacts/BuildArtifacts.ts
  packages/lib/src/artifacts/Contract.ts
  packages/lib/src/artifacts/Contracts.ts
  packages/lib/src/index.ts
  packages/lib/src/project/AppProject.ts
  packages/lib/src/project/ProxyAdminProject.ts
  packages/lib/src/project/mixin/ProxyAdminProjectMixin.ts
  packages/lib/src/proxy/ProxyAdmin.ts
  packages/lib/src/utils/ContractAST.ts
  packages/lib/src/utils/Mixin.ts
  packages/lib/test/src/artifacts/Contract.test.js
  tests/cli/test/src/integration.test.js
Labels: status:review

#822 Adds `unpack` command
  .githooks/pre-commit
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/commands/index.ts
  packages/cli/src/commands/unpack.ts
  packages/cli/src/models/files/KitFile.ts
  packages/cli/src/models/files/index.ts
  packages/cli/src/models/files/kit-config.schema.json
  packages/cli/src/models/local/KitController.ts
  packages/cli/src/models/local/index.ts
  packages/cli/src/scripts/interfaces.ts
  packages/cli/src/scripts/unpack.ts
  packages/cli/src/utils/child.ts
  packages/cli/src/utils/patch.ts
  packages/cli/src/utils/spinner.ts
  packages/cli/test/commands/share.js
  packages/cli/test/commands/unpack.test.js
  packages/cli/test/scripts/unpack.test.js
  packages/lib/package-lock.json
  packages/lib/package.json
  tsconfig.json
Labels: component:cli, kind:enhancement, status:ready-to-merge

#818 Implement function to look for project root dir
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/bin/helpers.ts
  packages/cli/src/bin/zos-cli.ts
  packages/cli/src/commands/add.ts
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/link.ts
  packages/cli/src/commands/push.ts
  packages/cli/test/bin/helpers.test.js
Labels: status:ready-to-merge
