Repository OpenZeppelin/openzeppelin-sdk, pull requests merged in 2019-05, with the labels that each got.

#823 Transfer command
  packages/cli/src/commands/index.ts
  packages/cli/src/commands/transfer.ts
  packages/cli/src/models/network/TransactionController.ts
  packages/cli/src/prompts/prompt.ts
  packages/cli/src/scripts/index.ts
  packages/cli/src/scripts/transfer.ts
  packages/cli/src/utils/units.ts
  packages/cli/test/commands/share.js
  packages/cli/test/commands/transfer.test.js
  packages/cli/test/scripts/transfer.test.js
  packages/lib/src/artifacts/ZWeb3.ts
  packages/lib/src/utils/Migrator.ts
  packages/lib/src/utils/Transactions.ts
  packages/lib/test/src/artifacts/ZWeb3.test.js
  packages/lib/test/src/utils/Transactions.test.js
Labels: status:ready-to-merge

#836 Retaining web3.js instance between multiple ZWeb3.web3() calls
  packages/lib/src/artifacts/ZWeb3.ts
Labels: status:ready-to-merge

#834 Balance command
  packages/cli/contracts/mocks/ERC20Fake.sol
  packages/cli/src/commands/balance.ts
  packages/cli/src/commands/index.ts
  packages/cli/src/models/network/TransactionController.ts
  packages/cli/src/scripts/balance.ts
  packages/cli/src/scripts/index.ts
  packages/cli/src/scripts/interfaces.ts
  packages/cli/src/scripts/transfer.ts
  packages/cli/src/utils/constants.ts
  packages/cli/src/utils/units.ts
  packages/cli/test/commands/balance.test.js
  packages/cli/test/commands/share.js
  packages/cli/test/scripts/balance.test.js
  packages/cli/test/utils/units.test.js
  packages/lib/src/artifacts/ZWeb3.ts
  packages/lib/test/src/artifacts/ZWeb3.test.js
  packages/lib/test/src/utils/Transactions.test.js
Labels: status:ready-to-merge

#840 Fix set-admin owner check
  packages/cli/src/commands/create2.ts
  packages/cli/src/models/TestHelper.ts
  packages/cli/src/models/dependency/Dependency.ts
  packages/cli/src/models/initializer/ConfigVariablesInitializer.ts
  packages/cli/src/models/local/LocalController.ts
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/src/models/network/ProjectDeployer.ts
  packages/cli/src/models/network/TransactionController.ts
  packages/cli/src/models/status/StatusChecker.ts
  packages/cli/src/scripts/interfaces.ts
  packages/lib/src/application/App.ts
  packages/lib/src/application/ImplementationDirectory.ts
  packages/lib/src/application/Package.ts
  packages/lib/src/artifacts/ZWeb3.ts
  packages/lib/src/helpers/copyContract.ts
  packages/lib/src/index.ts
  packages/lib/src/project/AppProject.ts
  packages/lib/src/project/BasePackageProject.ts
  packages/lib/src/project/BaseSimpleProject.ts
  packages/lib/src/project/PackageProject.ts
  packages/lib/src/project/ProxyAdminProject.ts
  packages/lib/src/project/SimpleProject.ts
  packages/lib/src/proxy/Proxy.ts
  packages/lib/src/proxy/ProxyAdmin.ts
  packages/lib/src/proxy/ProxyFactory.ts
  packages/lib/src/utils/Migrator.ts
  packages/lib/src/utils/Transactions.ts
Labels: component:lib, kind:bug, status:ready-to-merge

#842 Add TxParams Type
  packages/lib/src/artifacts/ZWeb3.ts
  packages/lib/src/utils/Transactions.ts
Labels: status:ready-to-merge

#848 `send-tx` command
  packages/cli/contracts/mocks/ImplV1.sol
  packages/cli/src/commands/balance.ts
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/index.ts
  packages/cli/src/commands/interfaces.ts
  packages/cli/src/commands/send-tx.ts
  packages/cli/src/commands/set-admin.ts
  packages/cli/src/commands/transfer.ts
  packages/cli/src/commands/update.ts
  packages/cli/src/models/local/ContractManager.ts
  packages/cli/src/models/local/LocalController.ts
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/src/models/network/TransactionController.ts
  packages/cli/src/models/status/EventsFilter.ts
  packages/cli/src/prompts/method-params.ts
  packages/cli/src/prompts/prompt.ts
  packages/cli/src/scripts/interfaces.ts
  packages/cli/src/scripts/send-tx.ts
  packages/cli/src/utils/contract.ts
  packages/cli/src/utils/input.ts
  packages/cli/test/commands/send-tx.test.js
  packages/cli/test/commands/share.js
  packages/cli/test/prompts/prompt.test.js
  packages/cli/test/scripts/send-tx.test.js
  packages/lib/contracts/mocks/InitializableMock.sol
  packages/lib/src/artifacts/Contract.ts
  packages/lib/src/artifacts/ZWeb3.ts
  packages/lib/test/src/artifacts/Contract.test.js
Labels: status:ready-to-merge

#850 Minimal proxies
  packages/cli/src/commands/create.ts
  packages/cli/src/models/files/ZosNetworkFile.ts
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/src/prompts/prompt.ts
  packages/cli/src/scripts/create.ts
  packages/cli/src/scripts/interfaces.ts
  packages/cli/test/commands/create.test.js
  packages/cli/test/scripts/create.test.js
  packages/cli/test/scripts/update.test.js
  packages/lib/contracts/upgradeability/ProxyFactory.sol
  packages/lib/src/index.ts
  packages/lib/src/project/AppProject.ts
  packages/lib/src/project/BaseSimpleProject.ts
  packages/lib/src/proxy/MinimalProxy.ts
  packages/lib/src/proxy/ProxyFactory.ts
  packages/lib/test/src/ProxyFactory.test.js
  packages/lib/test/src/project/ProxyProject.behaviour.js
Labels: status:ready-to-merge

#869 Fix #865, #867; Adds tutorial kit shortcut
  packages/cli/src/models/local/KitController.ts
  packages/cli/src/scripts/unpack.ts
  packages/cli/test/scripts/unpack.test.js
Labels: status:ready-to-merge

#866 Store proxy admin address on failed create
  packages/cli/contracts/mocks/ImplV1.sol
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/test/scripts/create.test.js
Labels: status:ready-to-merge

#847 Run push command before updating an instance
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/push.ts
  packages/cli/src/commands/update.ts
  packages/cli/test/prompts/prompt.test.js
  packages/cli/test/scripts/add.test.js
Labels: status:ready-to-merge

#877 Remove references to `lodash`
  packages/lib/package-lock.json
  packages/lib/package.json
  packages/lib/src/helpers/encodeCall.ts
  packages/lib/test/contracts/application/App.test.js
  packages/lib/test/contracts/application/ImplementationDirectory.test.js
  packages/lib/test/src/project/ProxyAdminProject.test.js
  packages/lib/test/src/project/SimpleProject.test.js
  packages/lib/test/src/validations/Layout.test.js
  packages/lib/test/src/validations/Validations.test.js
Labels: status:ready-to-merge

#876 [release/2.3] Run push before update and create
  packages/cli/src/bin/options.ts
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/push.ts
  packages/cli/src/commands/update.ts
  packages/cli/test/scripts/add.test.js
  packages/lib/package-lock.json
  packages/lib/package.json
  packages/lib/src/helpers/encodeCall.ts
  packages/lib/test/contracts/application/App.test.js
  packages/lib/test/contracts/application/ImplementationDirectory.test.js
  packages/lib/test/src/project/ProxyAdminProject.test.js
  packages/lib/test/src/project/SimpleProject.test.js
  packages/lib/test/src/validations/Layout.test.js
  packages/lib/test/src/validations/Validations.test.js
Labels: status:review

#882 Don't look for root dir on `zos unpack`
  packages/cli/src/bin/zos-cli.ts
Labels: status:review

#883 [release/2.3] Don't look for root dir on `zos unpack`
  packages/cli/src/bin/zos-cli.ts
Labels: status:review

#886 Fix prompt#contractsList with source fromLocal
  packages/cli/src/prompts/prompt.ts
  packages/cli/test/prompts/prompt.test.js
Labels: status:ready-to-merge

#885 [release/2.3] Fix prompt#contractsList with source fromLocal
  packages/cli/src/prompts/prompt.ts
  packages/cli/test/prompts/prompt.test.js
Labels: status:ready-to-merge

#881 Fix zos.json error message
  packages/cli/src/models/files/ZosNetworkFile.ts
  packages/cli/src/models/files/ZosPackageFile.ts
Labels: component:cli

#887 Add interactivity env
  packages/cli/src/commands/publish.ts
  packages/cli/src/prompts/prompt.ts
  packages/cli/test/prompts/prompt.test.js
  packages/cli/test/setup.js
Labels: status:ready-to-merge

#888 Output a message if no contracts were pushed
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/test/scripts/push.test.js
Labels: status:review

#880 Check duplicated artifact names
  packages/cli/contracts/mocks/ImplV1Clash.sol
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/test/helpers/captureLogs.js
  packages/cli/test/scripts/push.test.js
  packages/lib/src/artifacts/BuildArtifacts.ts
  packages/lib/src/utils/ContractAST.ts
  packages/lib/src/validations/index.ts
Labels: status:review

#893 Run contracts compilation on create
  packages/cli/src/commands/create.ts
Labels: status:review

#894 [release 2.3] Run contracts compilation on create
  packages/cli/src/commands/create.ts
Labels: status:review
