Repository OpenZeppelin/openzeppelin-sdk, pull requests merged in 2019-06, with the labels that each got.

#915 Remove ora and add `spinnies`
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/models/local/KitController.ts
  packages/cli/src/utils/spinner.ts
  packages/cli/test/scripts/unpack.test.js
Labels: status:ready-to-merge

#928 Fix directory path replacement
  packages/lib/src/artifacts/Contracts.ts
Labels: status:ready-to-merge

#940 Use relative paths in compiled artifacts
  packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts
  packages/cli/test/models/compiler/solidity/SolidityContractsCompiler.test.js
  packages/cli/test/models/compiler/solidity/SolidityProjectCompiler.test.js
Labels: status:review

#934 Handles swarm hash metadata for solidity 0.5.2
  packages/lib/package-lock.json
  packages/lib/package.json
  packages/lib/src/utils/Bytecode.ts
  packages/lib/test/src/utils/Bytecode.test.js
Labels: status:ready-to-merge, status:review

#956 Do not write invalid zos.json if compiling before init
  packages/cli/src/models/compiler/Compiler.ts
Labels: status:ready-to-merge

#953 Handle paths with spaces when compiling artifacts
  packages/cli/mocks/mock-stdlib-with-deps/node_modules/mock-dep/contracts/GreeterDep.sol
  packages/cli/mocks/mock-stdlib-with-deps/node_modules/mock-dep/contracts/subdep/GreeterSubdep.sol
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/models/compiler/solidity/ResolverEngineGatherer.ts
  packages/cli/src/models/files/ZosPackageFile.ts
  packages/cli/test/mocks/mock-stdlib with spaces/contracts/GreeterImpl.sol
  packages/cli/test/mocks/mock-stdlib with spaces/contracts/GreeterLib.sol
  packages/cli/test/mocks/mock-stdlib with spaces/package.json
  packages/cli/test/models/compiler/solidity/SolidityProjectCompiler.test.js
Labels: status:review

#969 Set logger in silent mode by default
  packages/cli/src/models/Verifier.ts
  packages/lib/src/utils/Logger.ts
Labels: status:ready-to-merge

#980 Fix error when printing errors in verbose mode
  packages/lib/package-lock.json
  packages/lib/package.json
  packages/lib/src/utils/Logger.ts
  packages/lib/test/setup.js
  packages/lib/test/src/utils/Logger.test.js
Labels: status:ready-to-merge

#978 Fix getting proxy address from ProxyCreated event
  packages/lib/src/proxy/ProxyFactory.ts
Labels: status:ready-to-merge

#985 Fix Verifier when using custom config
  packages/lib/package-lock.json
  packages/lib/package.json
  packages/lib/src/proxy/ProxyFactory.ts
  packages/lib/src/utils/Solidity.ts
Labels: status:ready-to-merge

#988 Improve inputs and outputs text messages
  packages/cli/src/commands/add.ts
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/init.ts
  packages/cli/src/commands/update.ts
  packages/cli/src/commands/verify.ts
  packages/cli/src/models/compiler/solidity/CompilerProvider.ts
  packages/cli/src/models/dependency/Dependency.ts
  packages/cli/src/models/local/LocalController.ts
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/src/models/network/TransactionController.ts
  packages/cli/src/prompts/prompt.ts
  packages/cli/src/scripts/add.ts
  packages/cli/src/scripts/remove.ts
  packages/cli/test/prompts/prompt.test.js
  packages/cli/test/scripts/call.test.js
  packages/cli/test/scripts/push.test.js
  packages/lib/package-lock.json
  packages/lib/package.json
  packages/lib/src/application/App.ts
  packages/lib/src/project/AppProject.ts
  packages/lib/src/project/BaseSimpleProject.ts
  packages/lib/src/project/ProxyAdminProject.ts
  packages/lib/src/proxy/ProxyAdmin.ts
  packages/lib/src/utils/ABIs.ts
Labels: status:ready-to-merge

#1018 Validate method args in interactive prompt
  packages/cli/src/prompts/method-params.ts
  packages/cli/src/utils/input.ts
  packages/lib/src/artifacts/ZWeb3.ts
Labels: status:ready-to-merge

#1036 Constants still work the normal way with zos
  packages/docs/docs/docs/writing_contracts.md
Labels: status:ready-to-merge

#1039 Add link to Solidity docs
  packages/docs/docs/docs/writing_contracts.md
Labels: kind:documentation, status:review
