Repository OpenZeppelin/openzeppelin-sdk, pull requests merged in 2019-11, with the labels that each got.

#1275 Upload user environment info in telemetry reports
  packages/cli/src/telemetry/index.ts
  packages/cli/src/telemetry/send-to-firebase.ts
  packages/cli/test/telemetry.test.js
  packages/docs/modules/ROOT/pages/faq.adoc
Labels: status:ready-to-merge

#1281 Fix typo in testing.adoc
  packages/docs/modules/ROOT/pages/testing.adoc
Labels: kind:documentation

#1285 Typechain support
  packages/cli/package.json
  packages/cli/src/commands/compile.ts
  packages/cli/src/commands/init.ts
  packages/cli/src/models/compiler/Compiler.ts
  packages/cli/src/models/compiler/ProjectCompilerOptions.ts
  packages/cli/src/models/compiler/Typechain.ts
  packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts
  packages/cli/src/models/files/ProjectFile.ts
  packages/cli/src/prompts/typechain.ts
  packages/cli/src/scripts/init.ts
  packages/cli/src/scripts/interfaces.ts
  packages/cli/test/commands/compile.test.js
  packages/cli/test/commands/init.test.js
  packages/cli/test/models/compiler/Compiler.test.js
  yarn.lock
Labels: status:ready-to-merge

#1288 Migrates SDK CLI tests to `test-environment`
  .circleci/config.yml
  packages/cli/package.json
  packages/cli/scripts/test.sh
  packages/cli/test/bin/helpers.test.js
  packages/cli/test/commands/create2.test.js
  packages/cli/test/commands/link.test.js
  packages/cli/test/config/TruffleConfig.test.js
  packages/cli/test/interface/ValidationLogger.test.js
  packages/cli/test/models/ContractManager.test.js
  packages/cli/test/models/Dependency.test.js
  packages/cli/test/models/ManifestVersion.test.js
  packages/cli/test/models/NetworkFile.test.js
  packages/cli/test/models/ProjectFile.test.js
  packages/cli/test/models/TestHelper.test.js
  packages/cli/test/prompts/prompt.test.js
  packages/cli/test/scripts/accounts.test.js
  packages/cli/test/scripts/add.test.js
  packages/cli/test/scripts/balance.test.js
  packages/cli/test/scripts/bump.test.js
  packages/cli/test/scripts/call.test.js
  packages/cli/test/scripts/check.test.js
  packages/cli/test/scripts/create.test.js
  packages/cli/test/scripts/freeze.test.js
  packages/cli/test/scripts/init.test.js
  packages/cli/test/scripts/link.test.js
  packages/cli/test/scripts/migrate.test.js
  packages/cli/test/scripts/publish.test.js
  packages/cli/test/scripts/push.test.js
  packages/cli/test/scripts/query-deployment.test.js
  packages/cli/test/scripts/query-signed-deployment.test.js
  packages/cli/test/scripts/remove.test.js
  packages/cli/test/scripts/send-tx.test.js
  packages/cli/test/scripts/session.test.js
  packages/cli/test/scripts/set-admin.test.js
  packages/cli/test/scripts/transfer.test.js
  packages/cli/test/scripts/unlink.test.js
  packages/cli/test/scripts/update.test.js
  packages/cli/test/scripts/verify.test.js
  packages/cli/test/setup.js
  packages/cli/test/telemetry.test.js
  packages/cli/test/utils/events.test.js
  packages/lib/test/src/utils/Transactions.test.js
  tsconfig.json
  yarn.lock
Labels: status:ready-to-merge

#1252 Libraries can link to other libraries with public functions
  packages/cli/contracts/mocks/ImplV1b.sol
  packages/cli/package.json
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/test/mocks/mock-stdlib-libdeps/contracts/GreeterLibLib.sol
  packages/cli/test/mocks/mock-stdlib-libdeps/contracts/GreeterLibWithLib.sol
  packages/cli/test/mocks/mock-stdlib-libdeps/contracts/GreeterLibWithLibImpl.sol
  packages/cli/test/mocks/mock-stdlib-libdeps/migrations/.gitkeep
  packages/cli/test/mocks/mock-stdlib-libdeps/package.json
  packages/cli/test/mocks/mock-stdlib-libdeps/truffle.js
  packages/cli/test/mocks/mock-stdlib-libdeps/zos.json
  packages/cli/test/mocks/mock-stdlib-libdeps/zos.test.json
  packages/cli/test/models/network/NetworkController.test.js
  yarn.lock
Labels: status:review
