Repository OpenZeppelin/openzeppelin-sdk, pull requests merged in 2019-02, with the labels that each got.

#567 Parse scientific notation numbers in input.ts.
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/utils/input.ts
  packages/cli/test/utils/input.test.js
  packages/lib/package.json
Labels: status:review

#625 Fix `ProxyAdmin` tests
  packages/lib/test/contracts/ProxyAdmin.test.js
Labels: status:review

#631 Update truffle-flattener version
  packages/lib/package-lock.json
  packages/lib/package.json
Labels: status:ready-to-merge, status:review

#629 Rename ZosContract to Contract
  packages/cli/src/interface/ValidationLogger.ts
  packages/cli/src/models/dependency/Dependency.ts
  packages/cli/src/models/files/ZosNetworkFile.ts
  packages/cli/src/models/local/LocalController.ts
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/src/models/status/EventsFilter.ts
  packages/cli/src/scripts/create.ts
  packages/lib/src/application/App.ts
  packages/lib/src/application/ImplementationDirectory.ts
  packages/lib/src/application/Package.ts
  packages/lib/src/artifacts/Contract.ts
  packages/lib/src/artifacts/Contracts.ts
  packages/lib/src/helpers/copyContract.ts
  packages/lib/src/index.ts
  packages/lib/src/project/AppProject.ts
  packages/lib/src/project/BasePackageProject.ts
  packages/lib/src/project/BaseSimpleProject.ts
  packages/lib/src/project/ProxyAdminProject.ts
  packages/lib/src/project/SimpleProject.ts
  packages/lib/src/proxy/Proxy.ts
  packages/lib/src/proxy/ProxyAdmin.ts
  packages/lib/src/utils/ABIs.ts
  packages/lib/src/utils/Bytecode.ts
  packages/lib/src/utils/ContractAST.ts
  packages/lib/src/utils/Transactions.ts
  packages/lib/src/validations/InitialValues.ts
  packages/lib/src/validations/Initializers.ts
  packages/lib/src/validations/Instructions.ts
  packages/lib/src/validations/Storage.ts
  packages/lib/src/validations/index.ts
  packages/lib/test/src/ProxyAdmin.test.js
Labels: status:ready-to-merge

#650 Log `truffle compile` output outside if/else
  packages/cli/src/models/compiler/Compiler.ts
Labels: status:ready-to-merge

#651 Fix in ZWeb3#ganacheNode return statement
  packages/lib/src/artifacts/ZWeb3.ts
Labels: status:ready-to-merge

#652 Get accounts from `web3.eth` in ZWeb3 instead of getting them from `web3.eth.personal`.
  packages/lib/src/artifacts/ZWeb3.ts
Labels: status:ready-to-merge

#642 Fix etherscan mainnet url
  packages/cli/src/models/Verifier.ts
Labels: status:ready-to-merge

#654 Checksum `from` address to avoid addresses comparison fail
  packages/cli/src/models/initializer/ConfigVariablesInitializer.ts
  packages/cli/src/models/initializer/truffle/Truffle.ts
  packages/cli/src/models/network/Session.ts
  packages/lib/src/artifacts/ZWeb3.ts
  packages/lib/test/src/artifacts/ZWeb3.test.js
Labels: status:ready-to-merge

#660 Minor fixes for 2.1 documentation
  packages/cli/src/commands/verify.ts
  packages/docs/docs/docs/deploying.md
  packages/docs/docs/docs/writing_contracts.md
Labels: status:in-progress

#674 Fix blueprint.truffle.js not being available in cli/lib output
  packages/cli/package.json
  packages/cli/scripts/copy-files.sh
Labels: status:review

#676 Allow bump script to receive a branch as argument
  packages/docs/README.md
  packages/docs/package-lock.json
  packages/docs/package.json
  packages/docs/scripts/bump-docs.js
  packages/docs/scripts/generators.js
Labels: status:review

#681 Fix `cli` docs generation with react and typescript
  packages/cli/docs/bin/docs.ts
  packages/cli/docs/components/Command.tsx
  packages/cli/docs/components/Main.tsx
  packages/cli/docs/components/Shared.tsx
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/scripts/gen-docs.sh
  packages/cli/tsconfig.docs.json
Labels: status:review

#682 Upgrade truffle-flattener to version 1.3.0
  packages/lib/changelog.md
  packages/lib/package-lock.json
  packages/lib/package.json
Labels: status:ready-to-merge

#688 Remove vouching contracts doc gen from bump script
  packages/docs/scripts/bump-docs.js
  packages/docs/scripts/generators.js
Labels: status:review

#687 Prompt migration question for each network independently
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/publish.ts
  packages/cli/src/commands/set-admin.ts
  packages/cli/src/commands/update.ts
  packages/cli/src/models/files/ZosNetworkFile.ts
  packages/cli/src/models/files/ZosPackageFile.ts
  packages/cli/test/commands/share.js
Labels: status:ready-to-merge

#691 Creates ZepKit page inside the docs
  packages/docs/docs/docs/zepkit.md
  packages/docs/docs/website/i18n/en.json
  packages/docs/docs/website/sidebars.json
Labels: status:review

#692 Minor fixes for 2.1 docs
  packages/docs/docs/docs/erc20_onboarding.md
  packages/docs/docs/docs/zos_lib.md
Labels: status:review

#690 Minor changes to the 2.2 documentation
  examples/cli-with-deps/package-lock.json
  examples/cli-with-deps/package.json
  examples/dep-basic/package-lock.json
  examples/dep-basic/package.json
  examples/lib-complex/package-lock.json
  examples/lib-complex/package.json
  examples/lib-simple/package-lock.json
  examples/lib-simple/package.json
  examples/truffle-migrate/package-lock.json
  examples/truffle-migrate/package.json
  lerna.json
  packages/cli/changelog.md
  packages/cli/docs/bin/docs.ts
  packages/cli/docs/components/Command.tsx
  packages/cli/docs/components/Main.tsx
  packages/cli/docs/components/Shared.tsx
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/scripts/copy-files.sh
  packages/cli/scripts/gen-docs.sh
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/publish.ts
  packages/cli/src/commands/set-admin.ts
  packages/cli/src/commands/update.ts
  packages/cli/src/models/files/ZosNetworkFile.ts
  packages/cli/src/models/files/ZosPackageFile.ts
  packages/cli/src/models/initializer/truffle/Truffle.ts
  packages/cli/test/commands/share.js
  packages/cli/test/initializer/truffle/Truffle.test.js
  packages/cli/truffle-config.js
  packages/cli/tsconfig.docs.json
  packages/docs/README.md
  packages/docs/docs/docs/faq.md
  packages/docs/docs/docs/vouching.md
  packages/docs/package-lock.json
  packages/docs/package.json
  packages/docs/scripts/bump-docs.js
  packages/docs/scripts/generators.js
  packages/lib/changelog.md
  packages/lib/package-lock.json
  packages/lib/package.json
  packages/lib/src/artifacts/Contract.ts
  packages/lib/src/utils/ABIs.ts
  packages/lib/src/utils/Transactions.ts
  tests/cli-app/files/package.json.v1
  tests/cli-app/files/package.json.v2
  tests/cli-app/package-lock.json
  tests/cli-app/package.json
Labels: status:review

#686 Updates the documentation regarding ProxyAdmin in zos 2.2
  packages/docs/docs/docs/architecture.md
  packages/docs/docs/docs/configuration.md
  packages/docs/docs/docs/pattern.md
  packages/docs/package-lock.json
Labels: status:review

#677 Updates the documentation guides for the zos 2.2 release
  packages/docs/docs/docs/deploying.md
  packages/docs/docs/docs/erc20_onboarding.md
  packages/docs/docs/docs/linking.md
  packages/docs/docs/docs/upgrading.md
  packages/docs/docs/docs/zos_lib.md
Labels: status:review

#699 Fix link to ProxyAdmin in docs
  packages/docs/docs/docs/new_2.2.md
  packages/docs/docs/website/versioned_docs/version-2.2.0/new_2.2.md
Labels: status:ready-to-merge

#711 Fix error while trying to get zosversion from commmand
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/publish.ts
  packages/cli/src/commands/set-admin.ts
  packages/cli/src/commands/update.ts
  packages/cli/src/models/files/ZosNetworkFile.ts
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/src/utils/prompt-migration.ts
Labels: status:review

#710 Specify truffle config file name on error
  packages/cli/src/models/initializer/truffle/Truffle.ts
  packages/cli/test/initializer/truffle/Truffle.test.js
Labels: status:review

#728 Added a note on calling overloaded functions with Truffle 4 and 5.
  packages/docs/docs/docs/testing.md
Labels: status:review

#730 Interactive add
  packages/cli/src/commands/add.ts
  packages/cli/src/models/initializer/truffle/Truffle.ts
  packages/cli/src/utils/prompt.ts
  packages/cli/test/initializer/truffle/Truffle.test.js
  packages/cli/test/scripts/add.test.js
  packages/cli/test/scripts/push.test.js
Labels: status:review

#698 Commented about not interacting with logic contracts in the deploying guide
  packages/docs/docs/docs/deploying.md
Labels: status:review

#724 New example: 'dynamic-instance`
  .travis.yml
  examples/creating-instances-from-solidity/.gitignore
  examples/creating-instances-from-solidity/contracts/Factory.sol
  examples/creating-instances-from-solidity/contracts/Instance.sol
  examples/creating-instances-from-solidity/index.js
  examples/creating-instances-from-solidity/migrations/.gitkeep
  examples/creating-instances-from-solidity/package-lock.json
  examples/creating-instances-from-solidity/package.json
  examples/creating-instances-from-solidity/test/test.js
  examples/creating-instances-from-solidity/truffle-config.js
  packages/docs/docs/docs/faq.md
Labels: status:review

#737 Initialize ZWeb3 without a provider
  packages/lib/src/artifacts/ZWeb3.ts
  packages/lib/test/src/artifacts/ZWeb3.test.js
Labels: status:review

#709 Remove network & local ControllerFor
  packages/cli/src/models/TestHelper.ts
  packages/cli/src/models/local/ControllerFor.ts
  packages/cli/src/models/local/LocalController.ts
  packages/cli/src/models/local/index.ts
  packages/cli/src/models/network/ControllerFor.ts
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/src/models/network/index.ts
  packages/cli/src/scripts/add-all.ts
  packages/cli/src/scripts/add.ts
  packages/cli/src/scripts/bump.ts
  packages/cli/src/scripts/check.ts
  packages/cli/src/scripts/compare.ts
  packages/cli/src/scripts/create.ts
  packages/cli/src/scripts/freeze.ts
  packages/cli/src/scripts/init.ts
  packages/cli/src/scripts/link.ts
  packages/cli/src/scripts/publish.ts
  packages/cli/src/scripts/pull.ts
  packages/cli/src/scripts/push.ts
  packages/cli/src/scripts/remove.ts
  packages/cli/src/scripts/set-admin.ts
  packages/cli/src/scripts/status.ts
  packages/cli/src/scripts/unlink.ts
  packages/cli/src/scripts/update.ts
  packages/cli/src/scripts/verify.ts
  packages/cli/test/scripts/status.test.js
Labels: status:review

#630 Parse ZosContract#new arguments
  packages/cli/test/scripts/migrate.test.js
  packages/lib/contracts/mocks/WithStructInConstructor.sol
  packages/lib/src/artifacts/Contract.ts
  packages/lib/src/artifacts/Contracts.ts
  packages/lib/src/utils/Transactions.ts
  packages/lib/test/contracts/ProxyAdmin.test.js
  packages/lib/test/contracts/application/App.test.js
  packages/lib/test/contracts/application/ImplementationDirectory.test.js
  packages/lib/test/contracts/application/ManagePackages.behavior.js
  packages/lib/test/contracts/application/ManageProxies.behavior.js
  packages/lib/test/contracts/application/Package.test.js
  packages/lib/test/src/ProxyAdmin.test.js
  packages/lib/test/src/artifacts/Contract.test.js
  packages/lib/test/src/utils/Migrator.test.js
Labels: status:review

#740 Some fixes on OFRBG's improvements to the lib-simple example
  .travis.yml
  examples/lib-simple/.babelrc
  examples/lib-simple/contracts/MyContract_v0.sol
  examples/lib-simple/contracts/MyContract_v1.sol
  examples/lib-simple/index.js
  examples/lib-simple/package-lock.json
  examples/lib-simple/package.json
  examples/lib-simple/test/main.test.js
  examples/lib-simple/test/setup.js
  examples/lib-simple/truffle.js
Labels: status:ready-to-merge

#745 Interactive verify
  packages/cli/src/commands/add.ts
  packages/cli/src/commands/init.ts
  packages/cli/src/commands/verify.ts
  packages/cli/src/models/initializer/truffle/Truffle.ts
  packages/cli/src/utils/prompt.ts
  packages/cli/test/commands/verify.test.js
  packages/cli/test/initializer/truffle/Truffle.test.js
  packages/cli/test/utils/prompt.test.js
Labels: status:review

#738 Improvements to the testing guide
  packages/docs/docs/docs/faq.md
  packages/docs/docs/docs/testing.md
Labels: status:review

#750 Interactive link and unlink
  packages/cli/src/bin/options.ts
  packages/cli/src/commands/link.ts
  packages/cli/src/commands/unlink.ts
  packages/cli/src/models/dependency/Dependency.ts
  packages/cli/src/models/files/ZosPackageFile.ts
  packages/cli/src/models/local/LocalController.ts
  packages/cli/src/scripts/link.ts
  packages/cli/src/scripts/unlink.ts
  packages/cli/src/utils/prompt.ts
  packages/cli/test/commands/link.test.js
  packages/cli/test/models/ZosPackageFile.test.js
Labels: status:in-progress
