Repository OpenZeppelin/openzeppelin-sdk, pull requests merged in 2020-01, with the labels that each got.

#1362 Update ABI methods listing for solc 0.6
  packages/lib/package.json
  packages/lib/src/artifacts/Contract.ts
  packages/lib/src/utils/ContractAST.ts
  packages/lib/test/mocks/mock-solc-0.6/.openzeppelin/project.json
  packages/lib/test/mocks/mock-solc-0.6/build/contracts/Base.json
  packages/lib/test/mocks/mock-solc-0.6/build/contracts/Sample.json
  packages/lib/test/mocks/mock-solc-0.6/contracts/.gitkeep
  packages/lib/test/mocks/mock-solc-0.6/contracts/Sample.sol
  packages/lib/test/mocks/mock-solc-0.6/networks.js
  packages/lib/test/mocks/mock-solc-0.6/package.json
  packages/lib/test/src/artifacts/Contract.test.js
  yarn.lock
Labels: status:ready-to-merge

#1366 Rework upgrade.js example
  .circleci/config.yml
  .mergify.yml
  examples/lib-simple/.babelrc
  examples/lib-simple/contracts/MyContract_v1.sol
  examples/lib-simple/index.js
  examples/lib-simple/migrations/.gitkeep
  examples/lib-simple/package.json
  examples/lib-simple/test/main.test.js
  examples/lib-simple/test/setup.js
  examples/lib-simple/truffle.js
  examples/upgrades-library/.gitignore
  examples/upgrades-library/README.md
  examples/upgrades-library/contracts/MyContractV0.sol
  examples/upgrades-library/contracts/MyContractV1.sol
  examples/upgrades-library/index.js
  examples/upgrades-library/package.json
  examples/upgrades-library/test/main.test.js
  yarn.lock
Labels: status:to-review

#1369 Trim ZWeb3
  examples/creating-instances-from-solidity/index.js
  examples/upgrades-library/index.js
  packages/cli/src/commands/session.ts
  packages/cli/src/commands/set-admin.ts
  packages/cli/src/commands/transfer.ts
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/src/models/network/TransactionController.ts
  packages/cli/src/scripts/accounts.ts
  packages/cli/src/utils/constants.ts
  packages/cli/src/utils/input.ts
  packages/cli/test/scripts/accounts.test.js
  packages/cli/test/scripts/push.test.js
  packages/cli/test/scripts/transfer.test.js
  packages/docs/modules/ROOT/pages/zos-lib.adoc
  packages/lib/src/artifacts/Contract.ts
  packages/lib/src/artifacts/ZWeb3.ts
  packages/lib/src/helpers/encodeCall.ts
  packages/lib/src/proxy/MinimalProxy.ts
  packages/lib/src/proxy/Proxy.ts
  packages/lib/src/utils/ABIs.ts
  packages/lib/src/utils/Transactions.ts
  packages/lib/test/contracts/application/ManageProxies.behavior.js
  packages/lib/test/contracts/upgradeability/AdminUpgradeabilityProxy.behaviour.js
  packages/lib/test/contracts/upgradeability/UpgradeabilityProxy.behaviour.js
  packages/lib/test/contracts/upgradeability/storageSlot.test.js
  packages/lib/test/src/artifacts/ZWeb3.test.js
  packages/lib/test/src/utils/Transactions.test.js
Labels: status:ready-to-merge

#1381 Refactor package.json commands
  packages/cli/package.json
  packages/lib/package.json
Labels: status:ready-to-merge

#1382 Stop interactive create or update on validation errors
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/push.ts
  packages/cli/src/commands/update.ts
Labels: status:ready-to-merge

#1385 Validate constructors in ancestor contracts
  packages/cli/src/interface/ValidationLogger.ts
  packages/cli/test/interface/ValidationLogger.test.js
  packages/lib/contracts/mocks/Invalid.sol
  packages/lib/src/artifacts/BuildArtifacts.ts
  packages/lib/src/artifacts/Contract.ts
  packages/lib/src/utils/ContractAST.ts
  packages/lib/src/validations/Constructors.ts
  packages/lib/src/validations/index.ts
  packages/lib/test/mocks/mock-dependency/contracts/DependencyInvalid.sol
  packages/lib/test/src/validations/Validations.test.js
Labels: status:ready-to-merge

#1394 Catch empty networks in network configuration files
  packages/cli/src/models/config/ConfigManager.ts
  packages/cli/src/models/config/NetworkConfig.ts
  packages/cli/src/models/config/TruffleConfig.ts
  packages/cli/src/prompts/prompt.ts
  packages/cli/test/prompts/prompt.test.js
Labels: status:ready-to-merge, status:to-review

#1393 Rework web3 timeouts
  packages/cli/src/bin/options.ts
  packages/cli/src/commands/session.ts
  packages/cli/src/models/config/ConfigManager.ts
  packages/cli/src/models/network/Session.ts
  packages/cli/src/scripts/interfaces.ts
  packages/cli/src/scripts/session.ts
  packages/cli/test/commands/session.test.js
  packages/cli/test/config/ConfigManager.test.js
  packages/cli/test/scripts/session.test.js
  packages/lib/src/artifacts/Contracts.ts
  packages/lib/src/artifacts/ZWeb3.ts
  packages/lib/src/helpers/copyContract.ts
  packages/lib/src/utils/Transactions.ts
  packages/lib/test/src/artifacts/Contracts.test.js
  packages/lib/test/src/artifacts/ZWeb3.test.js
  packages/lib/test/src/utils/Transactions.test.js
Labels: status:ready-to-merge

#1384 Store relative paths in project file
  packages/cli/src/models/dependency/Dependency.ts
  packages/cli/src/models/files/ProjectFile.ts
  packages/cli/test/models/ProjectFile.test.js
Labels: status:ready-to-merge

#1376 Non-upgradeable deploys, round 2
  packages/cli/contracts/mocks/SimpleNonUpgradeable.sol
  packages/cli/contracts/mocks/WithConstructorNonUpgradeable.sol
  packages/cli/contracts/mocks/WithLibraryNonUpgradeable.sol
  packages/cli/package.json
  packages/cli/src/bin/options.ts
  packages/cli/src/bin/program.ts
  packages/cli/src/commands/create.ts
  packages/cli/src/commands/deploy/action.ts
  packages/cli/src/commands/deploy/index.ts
  packages/cli/src/commands/deploy/spec.ts
  packages/cli/src/commands/index.ts
  packages/cli/src/commands/session.ts
  packages/cli/src/models/config/ConfigManager.ts
  packages/cli/src/models/files/NetworkFile.ts
  packages/cli/src/models/files/ProjectFile.ts
  packages/cli/src/models/local/ContractManager.ts
  packages/cli/src/models/network/NetworkController.ts
  packages/cli/src/models/network/Session.ts
  packages/cli/src/models/network/defaults.ts
  packages/cli/src/prompts/choices.ts
  packages/cli/src/prompts/prompt.ts
  packages/cli/src/register-command.ts
  packages/cli/src/scripts/interfaces.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/src/telemetry/send-to-firebase.ts
  packages/cli/src/utils/input.ts
  packages/cli/test/commands/deploy.test.ts
  packages/cli/test/scripts/session.test.js
  packages/cli/test/telemetry.test.js
  packages/lib/src/artifacts/Contract.ts
  packages/lib/src/artifacts/Contracts.ts
  packages/lib/src/errors.ts
  packages/lib/src/index.ts
  yarn.lock
Labels: status:to-review

#1390 Add Migrate CLI versions document
  packages/cli/docs/modules/ROOT/nav.adoc
  packages/cli/docs/modules/ROOT/pages/migrate-cli-versions.adoc
Labels: status:to-review

#1370 Feature/contracts transpiler
  packages/transpiler/.eslintignore
  packages/transpiler/.eslintrc.js
  packages/transpiler/.gitignore
  packages/transpiler/.prettierrc.js
  packages/transpiler/LICENSE
  packages/transpiler/package.json
  packages/transpiler/src/index.ts
  packages/transpiler/src/solc/artifact.ts
  packages/transpiler/src/solc/ast-node.ts
  packages/transpiler/src/solc/ast-utils.ts
  packages/transpiler/src/solc/get-inheritance-chain.ts
  packages/transpiler/src/solc/schemas/ast.ts
  packages/transpiler/src/transformation.ts
  packages/transpiler/src/transformations/append-directive.ts
  packages/transpiler/src/transformations/build-super-calls-for-chain.ts
  packages/transpiler/src/transformations/fix-import-directives.ts
  packages/transpiler/src/transformations/get-var-inits.ts
  packages/transpiler/src/transformations/index.ts
  packages/transpiler/src/transformations/prepend-base-class.ts
  packages/transpiler/src/transformations/purge-contracts.ts
  packages/transpiler/src/transformations/purge-var-inits.ts
  packages/transpiler/src/transformations/transform-constructor.ts
  packages/transpiler/src/transformations/transform-contract-name.ts
  packages/transpiler/src/transformations/transform-parents.ts
  packages/transpiler/src/transpiler.ts
  packages/transpiler/test/solc-0.5/.openzeppelin/project.json
  packages/transpiler/test/solc-0.5/contracts/ClassInheritance.sol
  packages/transpiler/test/solc-0.5/contracts/ComplexConstructor.sol
  packages/transpiler/test/solc-0.5/contracts/DiamondInheritance.sol
  packages/transpiler/test/solc-0.5/contracts/ElementaryTypes.sol
  packages/transpiler/test/solc-0.5/contracts/ElementaryTypesWithConstructor.sol
  packages/transpiler/test/solc-0.5/contracts/GLDToken.sol
  packages/transpiler/test/solc-0.5/contracts/Imports.sol
  packages/transpiler/test/solc-0.5/contracts/SimpleInheritance.sol
  packages/transpiler/test/solc-0.5/contracts/one/two/three/Deep.sol
  packages/transpiler/test/solc-0.5/jest.config.js
  packages/transpiler/test/solc-0.5/networks.js
  packages/transpiler/test/solc-0.5/package.json
  packages/transpiler/test/solc-0.5/test/ClassInheritance.test.ts
  packages/transpiler/test/solc-0.5/test/DiamondInheritance.test.ts
  packages/transpiler/test/solc-0.5/test/ElementaryTypes.test.ts
  packages/transpiler/test/solc-0.5/test/ElementaryTypesWithConstructor.test.ts
  packages/transpiler/test/solc-0.5/test/GLDToken.test.ts
  packages/transpiler/test/solc-0.5/test/Imports.ts
  packages/transpiler/test/solc-0.5/test/LocalConract.behaviour.ts
  packages/transpiler/test/solc-0.5/test/SimpleInheritance.test.ts
  packages/transpiler/test/solc-0.5/test/__snapshots__/ClassInheritance.test.ts.snap
  packages/transpiler/test/solc-0.5/test/__snapshots__/DiamondInheritance.test.ts.snap
  packages/transpiler/test/solc-0.5/test/__snapshots__/ElementaryTypes.test.ts.snap
  packages/transpiler/test/solc-0.5/test/__snapshots__/ElementaryTypesWithConstructor.test.ts.snap
  packages/transpiler/test/solc-0.5/test/__snapshots__/GLDToken.test.ts.snap
  packages/transpiler/test/solc-0.5/test/__snapshots__/SimpleInheritance.test.ts.snap
  packages/transpiler/test/solc-0.5/test/compile.test.ts
  packages/transpiler/test/solc-0.5/test/setup.ts
  packages/transpiler/test/solc-0.5/tsconfig.json
  packages/transpiler/test/solc-0.5/yarn.lock
  packages/transpiler/tsconfig.json
  yarn.lock
Labels: status:to-review

#1413 Support solidity 0.6 in Initializable contract
  package.json
  packages/cli/test/utils/solidity.test.js
  packages/lib/contracts/Initializable.sol
  packages/lib/package.json
  packages/lib/test/contracts/Initializable.test.js
  tests/mocks/mock-dependency/.gitignore
  tests/mocks/mock-dependency/build/contracts/Greeter.json
  tests/mocks/mock-dependency/contracts/DependencyInvalid.sol
  tests/mocks/mock-dependency/contracts/DependencyStorageMock.sol
  tests/mocks/mock-dependency/contracts/Greeter.sol
  tests/mocks/mock-dependency/migrations/.gitkeep
  tests/mocks/mock-dependency/package-lock.json
  tests/mocks/mock-dependency/package.json
  tests/mocks/mock-dependency/truffle.js
  tests/mocks/mock-solc-0.6/.gitignore
  tests/mocks/mock-solc-0.6/.openzeppelin/project.json
  tests/mocks/mock-solc-0.6/build/contracts/Base.json
  tests/mocks/mock-solc-0.6/build/contracts/Initializable.json
  tests/mocks/mock-solc-0.6/build/contracts/InitializableMock.json
  tests/mocks/mock-solc-0.6/build/contracts/Sample.json
  tests/mocks/mock-solc-0.6/build/contracts/SampleChild.json
  tests/mocks/mock-solc-0.6/build/contracts/SampleFather.json
  tests/mocks/mock-solc-0.6/build/contracts/SampleGramps.json
  tests/mocks/mock-solc-0.6/build/contracts/SampleHuman.json
  tests/mocks/mock-solc-0.6/build/contracts/SampleMother.json
  tests/mocks/mock-solc-0.6/contracts/.gitkeep
  tests/mocks/mock-solc-0.6/contracts/Sample.sol
  tests/mocks/mock-solc-0.6/contracts/initializable/Initializable.sol
  tests/mocks/mock-solc-0.6/contracts/initializable/InitializableMock.sol
  tests/mocks/mock-solc-0.6/contracts/initializable/MultipleInheritanceInitializableMocks.sol
  tests/mocks/mock-solc-0.6/networks.js
  tests/mocks/mock-solc-0.6/package.json
  yarn.lock
Labels: status:ready-to-merge

#1415 Do not ask for typechain support on compile outside a project
  packages/cli/package.json
  packages/cli/src/commands/compile.ts
  packages/cli/src/models/compiler/Compiler.ts
  packages/cli/src/models/compiler/Typechain.ts
  packages/cli/src/prompts/typechain.ts
  packages/cli/src/scripts/interfaces.ts
  packages/cli/test/commands/compile.test.js
  yarn.lock
Labels: status:ready-to-merge, status:to-review
